### ISSUE TITLE
Should we remove one of the redundant methods to get the result in Attempt?

### ISSUE THREAD

**Issue by sleberknight** [kiwiproject/retrying-again#27]
The `Attempt` class has two methods that are basically the same thing:

* `T get()`
* `T getResult()`

The `getResult()` method's implementation actually just calls `get()`. The was the original design from the original guava-retrier library, when `Attempt` was an `interface`.

**Questions:**
1. Should we remove one of these (redundant) methods?
2. If we want to remove to remove one of them, which one?

**Comment by terezivy** [comment]
I say drop the getResult method, given that the class itself is an attempt.

**Comment by sleberknight** [comment]
> I say drop the getResult method, given that the class itself is an attempt.

But remember that an `Attempt` has _either_ a result _or_ an exception, and has `getException()`. So, wouldn't `getResult()` more closely parallel the `getException()` method?

**Comment by chrisrohr** [comment]
Due to the getException part, I think we should keep the methods explicit

**Comment by sleberknight** [comment]
This will be be done in #50 (this should have been a discussion...)
